services:
# the sql containers
 mysql-users:
  container_name: users-sql
  image: mysql
  build: ./sql/users
  env_file: ./sql/users/.env
  ports: 
  - "3307:3306"
  volumes:
  - ./sql:/docker-entrypoint-initdb.d

# the main app
 main-app:
  build: ./app/main
  env_file: ./app/.env
  volumes:
  - ./app/main:/app/main

# the server to process requests
 service-server:
  build: ./server
  env_file: ./server/.env
  volumes:
  - ./server/backend:/server/main/backend